### ISSUE TITLE
the presence of subcommands is not mentioned in the usage message

### ISSUE THREAD

**Issue by marco-m** [alexflint/go-arg#103]
to make this issue easier to discuss about, I created a corresponding PR #102.
That PR is not meant to be merged as-is, it is more a reproducible example of what this
ticket is about.

Running the tests in that PR will fail, and the expected outcome is what I am suggesting
in this ticket.

## Case 1, backward-compatible

Consider the example [Example_helpTextWithSubcommand()](https://github.com/alexflint/go-arg/blob/master/example_test.go#L171) in example_test.go.

Although it supports two subcommands, `get` and `list`, they are not mentioned. More in details:

It is called with

    os.Args = split("./example --help")

and it outputs:

    Usage: example [--verbose]
    [..snip..]

while in my opinion it should output something similar to:

    Usage: example [--verbose] <command> [<args>]
    [..snip..]

to hint to the user that the program supports and wants subcommands.

## Case 2, non backward-compatible

Another example:

Consider the same configuration in Example_helpTextWithSubcommand(), but this time
imagine that the program is called with no arguments:

    os.Args = split("./example")

it would output nothing

while I think that it should output

    Usage: example [--verbose] <command> [<args>]
    error: <command> is required

This is non backward-compatible because it would change the behavior of `MustParse`, since currently it returns to the caller, while this change would make `MustParse` terminate the program.

If what is proposed in this ticket (or a variant) is considered reasonable, I will be happy
to propose an implementation PR for further discussion.

**Comment by alexflint** [comment]
Hey @marco-m, thank you for this thorough and clear issue report.

I agree with case 1 and thank you for the PR to address it. I've left a small comment on that PR but otherwise ready to merge.

Regarding case 2: It should be possible, using go-arg, to have a program that accepts subcommands, but also does something else when no subcommands are specified. I can't think of a good way for users to specify this, so I decided to have the library not throw an error if there is no subcommand. So for now I don't think we should make this change. To throw an error when no subcommand is provided you could do something like

```go
p := arg.MustParse(&args)
if p.Subcommand() == nil {
  p.Fail("missing subcommand")
}
```

Even though this is a bit more verbose, it's also quite clear what's happening, and this code should only be needed at most once per program, which doesn't seem too bad. You may already be doing something similar to this.

It would be good to add an example showing this pattern because I imagine it will come up frequently.

**Comment by marco-m** [comment]
Hello, I understand the reasoning, and I think that the approach you propose is the best trade-off.
I ended up with something similar to the example you give, and I am content with it.

I will give it a try with the example, although now I wonder if you mean an executable example in example_test.go or in the README.

**Comment by alexflint** [comment]
@marco-m It would be best to add both an executable example in that file and an example in the readme.

**Comment by marco-m** [comment]
> It would be best to add both an executable example in that file and an example in the readme.

Unfortunately I started by adding to example_test.go, but it didn't work because Go "testable examples" expect the program to output to stdout, while in this case we are using stderr.
