### ISSUE TITLE
When sending unknown parameter all parameters will be empty because of this line

### ISSUE THREAD

**Issue by gunesahmet** [alexflint/go-arg#128]
https://github.com/alexflint/go-arg/blob/master/parse.go#L559
Maybe you can set config ignoring unknown params or just skip with `continue`
Example: 

```
var args struct {
	FirstParam 		string `arg:"--first"`
	SecondParam 		string `arg:"--second"`
}
arg.MustParse(&args)
```

if i run like this that's good working
```
./command --first=1 --second=2
FirstParam = 1
SecondParam = 2
```

But like this all params even right setted params will be empty
```
./command --zero=0 --first=1 --second=2
FirstParam =
SecondParam =
```

**Comment by alexflint** [comment]
Yes we could have an option for this but it gets a bit dicey because we then don't know which tokens are positional arguments and which are the values for unknown arguments. For example if I write

```
./program --some-unknown-flag abc
```
Then should we ignore "abc" assuming that it is associated with "--some-unknown-flag", or should we use "abc" as the first positional argument? This depends on whether "--some-unknown-flag" is a boolean, in which case we would interpret "abc" as a positional argument, or a string, in which case we would interpret "abc" as the value for the "--some-unknown-flag" option. But if "--some-unknown-flag" is unknown, then we don't known whether it should be treated as a boolean, string, or something else.

Nevertheless it seems reasonable to offer something here. I'm open to suggestions.

**Comment by gunesahmet** [comment]
I add `continue` when coming unknown params. That's fix my problem. I can look later for solution. When i complete i ll send completed code.

**Comment by alexflint** [comment]
Closing for now
