### ISSUE TITLE
Failure output stream

### ISSUE THREAD

**Issue by nxshock** [alexflint/go-arg#183]
Why `MustParse()` writes errors to `stdout` insead of `stderr`? I think all errors should be directed to `stderr`.

**Comment by alexflint** [comment]
In the tools that I build, I like command-line tools to write everything to stdout, since if there is a mixture of stdout and stderr then lines can appear out-of-order relative to the order in which they were generated. On the other hand, I typically have server applications -- web apps and so forth -- write to stderr. The reason MustParse writes to stdout instead of stderr is that I anticipated that it would be used most often in command-line tools.

But you can make it write to stderr with something like:
```
var args struct {
  ...
}
p, err := arg.Parse(&args)
if err != nil {
  p.WriteUsage(os.Stderr)
  fmt.Fprintf(os.Stderr, "error: %v", err)
}
```

**Comment by alexflint** [comment]
I'm closing this for now but feel free to leave further comments if you would like to discuss more.
