### ISSUE TITLE
Args with type parameters don't work when not passed

### ISSUE THREAD

**Issue by slnt** [alexflint/go-arg#184]
So I have this struct I've defined:

```go
type JSONValue[T any] struct {
	val T
}

func (v *JSONValue[T]) Get() T {
	return v.val
}

func (v *JSONValue[T]) UnmarshalText(data []byte) error {
	return json.Unmarshal(data, &v.val)
}
```

I am trying to use it my args like this:
```go
type Args struct {
    // ...
    Environment JSONValue[map[string]string] `arg:"--env"`
    // ....
}
```
(It has to be this way for Reasons™)

When I pass `--env` it works just fine, however if I omit it then I get the following error:
```
error: error processing default value for --environment: invalid character 'm' looking for beginning of object key string
```

**Comment by alexflint** [comment]
Do you have a default value configured, perhaps with a struct tag like `default:"...">`?

**Comment by slnt** [comment]
I do not have any default value configured. :(

**Comment by slnt** [comment]
Is this perhaps related to #160? I was expecting that the arg not being passed would have just left the zero value in place.

**Comment by alexflint** [comment]
The basic problem here is that when a struct has a non-zero value, we take its value and turn it into a string to use as a default value in help text. Then, later, when a struct supports `encoding.TextUnmarshaler` we decode its default value from string. However, the stringified version of `JSONValue` looks like `map[string]string{...}` whereas the `UnmarshalText` function on the same struct expects json, not go-style structs. In the end it was a mistake to assume that we could turn structs into strings and then back into structs, and we shouldn't assume that we can do so.

The fix should be to store default values both as strings and structs, and do the decoding from strings to structs in `cmdFromStruct` rather than in `Parse`.
