### ISSUE TITLE
Usage of boolean parameters

### ISSUE THREAD

**Issue by skabashnyuk** [alexflint/go-arg#188]
Usage message of boolean parameters doesn't show environment variable name

```
ZapDevel             bool   `arg:"-d, --zap-devel, env" default:"false" help:"Development Mode defaults(encoder=consoleEncoder,logLevel=Debug,stackTraceLevel=Warn) Production Mode defaults(encoder=jsonEncoder,logLevel=Info,stackTraceLevel=Error)"`

```

shows
```
Usage:  ....  [--zap-devel] 

```
expected
```
Usage:  ....  [--zap-devel ZAPDEVEL] 

```

Somehow related to https://github.com/alexflint/go-arg/blob/ebd7a68a06bef58b87c1fd21c2e7db383adbcbf3/usage.go#L331-L333

**Comment by DreamingRaven** [comment]
@skabashnyuk Did you find a solution to this? I am also trying to use an env variable to trigger a bool flag. Unless I am missing something it does not seem to enable this by default.

While it is a bit odd to want this since an env variable is always a string, I was thinking if the env variable is present = true, and if absent = false. I can ofc always just use a string type but I figure this is cleaner.

**Comment by DreamingRaven** [comment]
No problem thanks for responding!
