### ISSUE TITLE
FEATURE REQUEST: "choices"

### ISSUE THREAD

**Issue by drkennetz** [alexflint/go-arg#208]
Hi team.

Something that I've found myself wanting is the ability to enforce that an argument is in a list of choices. For example, I am writing a tool that uses viper to parse a config. Viper has a list of valid config types that it supports. For example:

```
type args struct {
	Config string `arg:"required,-c,--config" help:"config file"`
	Type   string `arg:default:"" help:"the config type [json, toml, yaml, hcl, ini, env, xml]; if not passed, inferred from file ext"`
}
```
This is what I'm using now, and enforcing the type inside of the config parser.
It would be helpful to be able to do:
```
type args struct {
	Config string `arg:"required,-c,--config" help:"config file"`
	Type   string `arg:default:"" choices:"[json, toml, yaml, hcl, ini, env, java]" help:"the config type; if not passed, inferred from file ext"`
} 
```

If this exists already and I've missed it, sorry about that! If you'd like help working on it I'd be happy to take a stab.

**Comment by alexflint** [comment]
It doesn't exist yet. Thanks for the suggestion. I've considered it in the past. The reason I haven't implemented it previously is there is quite a bit of variability in how different applications want the multiple-choice thing to be setup. Sometimes you want to allow a blank value in addition to the allowed choices. Sometimes you want the choices to be case-sensitive and other times you want them to be case-insensitive. Sometimes you want to allow certain wildcard values.

In the end, user code that makes use of multiple-choice options will usually have a big switch statement somewhere anyway, even if the argument processing library does some initial validation for you. It will look something like this

```go
var args struct {
  Type string  `choices:"json, toml"`
}
p := arg.MustParse(&args)

switch p.Type {
  case "json":
    ....
  case "toml":
    ....
}
```

Now it seems to me that you might as well just add a "default" block to the switch, and do away with the struct tags altogether:

```go
var args struct {
  Type string
}
p := arg.MustParse(&args)

switch p.Type {
  case "json":
    ....
  case "toml":
    ....
  default:
    p.Fail("you must specify one of json or toml")
}
```

By doing it this way, the user has a lot of flexibility in how exactly the thing is set up. For example, to make it case insensitive you just use `switch strings.ToLower(args.Type)`. If you want to read the allowable formats, for example, from a configuration file, rather than hardcoding them, then you can do that when you have programmatic control over the things as a user.

The main down-side of doing it this way is that you usually have the list of allowed options in the help text, and you have to manually keep that up to date with the switch statement. But generally you will have the same problem with a "choices" tag, because you will most likely still have the big switch statement wherever it is that you make use of the flag, and you will still have to keep that switch statement up to date with the values in the "choices" tag.

So for these I have not implemented this within this library.

**Comment by drkennetz** [comment]
Hi Alex, thanks for taking the time to share your reasoning with me, I really appreciate that. 

It feels like you're providing a logical extension to one possibility of how a "choices" parameter could be used, and it makes sense. My reasoning for suggesting the implementation was simple and along the lines of:

"there are only n valid options for this argument, and so the argument parser should enforce that." 

How people decide to use that logic is up to them, and for "choices", I don't think you should provide any flexibility such as case insensitivity, wildcard expansion, etc. It's more of, here are the choices - pick one.

Personally, I've never choices in the way you describe above. I use them when I have a constrained system with allowable values (like supported config types), loadable system configurations, etc.

I generally use them as: these are the allowable options. 

I've obviously implemented this same logic one level past the argument parser in my application, which is okay, but they really aren't application logic. They are initial input logic, which seems appropriate for a parser.

Anyway, thanks for taking the time and sharing your reasoning - and I really like your library! Especially the subcommand parser :D. Thanks for all the work you do to make this available for everyone!
